### ISSUE TITLE
HLS/m3u8 support?

### ISSUE THREAD

**Issue by mathewjordan** [dkaoster/scrolly-video#31]
Hello @dkaoster, this absolutely fantastic. I'm attempting to get it to with HLS videos having .m3u8 extensions to support a digital humanities application. Is it possible in the current release?

The applicable media can be viewed here:
- https://dc.library.northwestern.edu/items/df34cea4-47e7-4f41-9a27-26cc671feabe 

And the three files I'm looking to prove a concept with are these: 
- https://stream.dc.library.northwestern.edu/5a/cc/f7/5f/-a/56/1-/4b/3c/-9/b4/5-/7d/cc/f7/03/90/e3/74-110-2.m3u8
- https://stream.dc.library.northwestern.edu/2b/c3/0b/3d/-1/3d/f-/42/39/-8/a5/9-/03/90/4f/8d/d4/a5/74-110-3.m3u8
- https://stream.dc.library.northwestern.edu/bf/8b/26/1f/-3/de/6-/44/3f/-a/d2/f-/f2/92/01/47/fa/ad/74-110-6.m3u8

**Comment by dkaoster** [comment]
Hi @mathewjordan! unfortunately ScrollyVideo is currently set up to use native browser APIs as much as possible, which seems like only Safari / iOS devices may support HLS via .m3u8. While you might get that to work on Safari, I'd recommend converting the files into a more universal format for use with ScrollyVideo.

**Comment by mathewjordan** [comment]
> Hi @mathewjordan! unfortunately ScrollyVideo is currently set up to use native browser APIs as much as possible, which seems like only Safari / iOS devices may support HLS via .m3u8. While you might get that to work on Safari, I'd recommend converting the files into a more universal format for use with ScrollyVideo.

Thanks @dkaoster, appreciate the response.
