### ISSUE TITLE
ViteJS + react  not provide an export named 'default'

### ISSUE THREAD

**Issue by AnthonY-Dole** [dkaoster/scrolly-video#35]
When you created a project with ViteJS + React, we have this error:

Uncaught SyntaxError: The requested module '/node_modules/scrolly-video/dist/ScrollyVideo.jsx' does not provide an export named 'default'

**Comment by dkaoster** [comment]
@AnthonY-Dole do you mind sharing your `vite.config.js` file?

**Comment by AnthonY-Dole** [comment]
Off course this is my vite config fil. It's just th default config file

`import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
});
`

**Comment by dkaoster** [comment]
That should fix it, I've bumped it to version `0.0.13` and have added an esm bundled version.

If you upgrade to the latest and import it with `import ScrollyVideo from 'scrolly-video/dist/ScrollyVideo.esm.jsx';` it should work.

**Comment by AnthonY-Dole** [comment]
working perfectly thanks
