### ISSUE TITLE
Video plays backwards if it has a parent with fixed dimensions

### ISSUE THREAD

**Issue by Asored-D** [dkaoster/scrolly-video#62]
Hi there!

I have noticed a strange problem which, unfortunately, severely restricts its use in some areas. As soon as Scrolly Video has a parent with a fixed width, the video is played in the wrong direction. It runs backwards.

As a basis to show the problem, I have slightly adapted the demo project. 

Pen: https://codepen.io/asored/pen/poqgKBr

The modifications are as follows:

1) The scroll video container got a parent that has a width of 800px.
2) The`full` parameter was set to `false`.

As you can see, the video now plays backwards when you scroll down - and forwards when you scroll up.

Is there a workaround to prevent this? We use ScrollyVideo in one of our products and our users would be totally grateful :)
Thanks a lot for your work guys! It's very much appreciated! ❤️

**Comment by dkaoster** [comment]
If you set the `full` parameter to false, you will likely also have to set `cover` to false. If I set `cover` to false on your codepen, it scrolls in the correct direction.

If you run into further issues due to custom placement, I would recommend setting `trackScroll` to false and writing your own listener and methods to update the `videoPercentage` value.

**Comment by Asored-D** [comment]
> If you set the `full` parameter to false, you will likely also have to set `cover` to false. If I set `cover` to false on your codepen, it scrolls in the correct direction.
> 
> If you run into further issues due to custom placement, I would recommend setting `trackScroll` to false and writing your own listener and methods to update the `videoPercentage` value.

Wow, that was fast! :-) Thanks! Setting `cover` to`false` will play the video in the correct direction, but not respecting the parent boundaries. The canvas will have `1920x1080px` and ignore the `800px` of the parent. Is this the expected behavior in that case? Or do I miss something?

**Comment by dkaoster** [comment]
yeah, unfortunately with custom placement like you have, you probably will also have to use a custom listener and video position logic

**Comment by Asored-D** [comment]
Alright. Thanks very much for clarifying!
