### ISSUE TITLE
Looked into using img-tag?

### ISSUE THREAD

**Issue by olekenneth** [dkaoster/scrolly-video#74]
Hi

I see you write that it won't work in safari in battery save mode. 

But have you tried using an img-tag?

Test here: https://codepen.io/shshaw/pen/MOMezY

**Comment by dkaoster** [comment]
I haven't heard of this, but I can't find whether this supports things like navigating to specific frames or adjusting the playback rate?

**Comment by tarsinzer** [comment]
it looks like it only focuses on streamlining the use of short, looping videos, potentially offering file size savings, but it unlikely can be utilised for scrolling purposes
